package com.wok.bodyhealth.prone;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.JsonParser;
import net.minecraft.util.Mth;
import net.minecraft.world.phys.Vec3;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;

/**
 * TAA 1.2.5 prone model as body-local hit boxes, generated by {@code tools/prone/k7_segments.js}.
 * Steady prone poses form a 37 x 9 grid over aim (-180..180, step 10) and {@link #PITCHES};
 * entering and leaving prone are 17 keyframes each at progress k/16.
 */
public final class ProneSegmentTables {
    public static final String RESOURCE = "/wok_body_health/prone/taa-1.2.5-segments.json";
    public static final double[] PITCHES = {-70, -45, -25, -10, 0, 10, 25, 45, 70};

    static final int AIM_COUNT = 37;
    static final int AIM_STEP = 10;
    static final int FRAME_COUNT = 17;
    private static final int GUN = 0;
    private static final int EMPTY = 1;
    private static final String[] VARIANTS = {"gun", "empty"};

    private static volatile boolean sharedResolved;
    private static ProneSegmentTables shared;

    /** [variant][aim index][pitch index] */
    private final BodyLayout[][][] steady;
    /** [variant] */
    private final BodyLayout[] crawl;
    /** [variant][frame] */
    private final Frame[][] enter;
    private final Frame[][] exit;
    private final double reachBound;

    /** One transition keyframe; {@code prone} is TAA's 0 (upright) to 1 (flat) body blend. */
    public record Frame(double prone, BodyLayout layout) {
    }

    private ProneSegmentTables(BodyLayout[][][] steady, BodyLayout[] crawl, Frame[][] enter, Frame[][] exit) {
        this.steady = steady;
        this.crawl = crawl;
        this.enter = enter;
        this.exit = exit;
        this.reachBound = computeReachBound();
    }

    /** Parses and validates a segment table. Every stored box is re-orthogonalised once here. */
    public static ProneSegmentTables load(InputStream in) throws IOException {
        try (Reader reader = new InputStreamReader(in, StandardCharsets.UTF_8)) {
            JsonObject root = object(JsonParser.parseReader(reader), "root");
            JsonObject steadyJson = object(root, "steady");
            JsonObject crawlJson = object(root, "crawlEnvelopeAABB");
            JsonObject enterJson = object(root, "enter");
            JsonObject exitJson = object(root, "exit");

            BodyLayout[][][] steady = new BodyLayout[VARIANTS.length][AIM_COUNT][PITCHES.length];
            BodyLayout[] crawl = new BodyLayout[VARIANTS.length];
            Frame[][] enter = new Frame[VARIANTS.length][];
            Frame[][] exit = new Frame[VARIANTS.length][];
            for (int variant = 0; variant < VARIANTS.length; variant++) {
                String name = VARIANTS[variant];
                JsonObject grid = object(steadyJson, name);
                for (int i = 0; i < AIM_COUNT; i++) {
                    for (int j = 0; j < PITCHES.length; j++) {
                        String key = steadyKey(i, j);
                        steady[variant][i][j] = layout(object(grid, key), "steady." + name + "." + key);
                    }
                }
                crawl[variant] = extentsLayout(object(crawlJson, name), "crawlEnvelopeAABB." + name);
                enter[variant] = frames(array(enterJson, name), "enter." + name);
                exit[variant] = frames(array(exitJson, name), "exit." + name);
            }
            return new ProneSegmentTables(steady, crawl, enter, exit);
        } catch (JsonParseException | IllegalStateException | UnsupportedOperationException
                 | NumberFormatException | ClassCastException e) {
            throw new IOException("Malformed prone segment table: " + e.getMessage(), e);
        }
    }

    /**
     * Shared table from {@link #RESOURCE}, loaded on first use. A failure is cached as well and
     * logged once; callers then get null and must fall back to the original hitbox.
     */
    public static ProneSegmentTables shared() {
        if (!sharedResolved) {
            synchronized (ProneSegmentTables.class) {
                if (!sharedResolved) {
                    shared = loadShared();
                    sharedResolved = true;
                }
            }
        }
        return shared;
    }

    private static ProneSegmentTables loadShared() {
        try (InputStream in = ProneSegmentTables.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                throw new IOException("Missing resource " + RESOURCE);
            }
            return load(in);
        } catch (IOException | RuntimeException e) {
            System.getLogger("wok_body_health/prone").log(System.Logger.Level.WARNING,
                    "Could not load the prone segment table; TAA prone poses fall back to the original hitbox", e);
            return null;
        }
    }

    /** Steady prone pose, bilinear over aim (wrapped) and pitch (clamped to +/-70). */
    public BodyLayout steady(boolean gun, double aimDeg, double pitchDeg) {
        double aim = Double.isFinite(aimDeg) ? Mth.wrapDegrees(aimDeg) : 0.0D;
        double aimSteps = (aim + 180.0D) / AIM_STEP;
        int i0 = Mth.clamp((int) Math.floor(aimSteps), 0, AIM_COUNT - 2);
        double a = Mth.clamp(aimSteps - i0, 0.0D, 1.0D);

        double pitch = Double.isFinite(pitchDeg)
                ? Mth.clamp(pitchDeg, PITCHES[0], PITCHES[PITCHES.length - 1]) : 0.0D;
        int j0 = 0;
        while (j0 < PITCHES.length - 2 && pitch > PITCHES[j0 + 1]) {
            j0++;
        }
        double b = Mth.clamp((pitch - PITCHES[j0]) / (PITCHES[j0 + 1] - PITCHES[j0]), 0.0D, 1.0D);

        BodyLayout[][] grid = steady[variant(gun)];
        return BodyLayout.blend(
                new BodyLayout[]{grid[i0][j0], grid[i0 + 1][j0], grid[i0][j0 + 1], grid[i0 + 1][j0 + 1]},
                new double[]{(1.0D - a) * (1.0D - b), a * (1.0D - b), (1.0D - a) * b, a * b});
    }

    /** Union of the crawl cycle at aim 0 / pitch 0 as axis-aligned boxes (only the limbs are used). */
    public BodyLayout crawlEnvelope(boolean gun) {
        return crawl[variant(gun)];
    }

    public Frame enter(boolean gun, double progress) {
        return interpolate(enter[variant(gun)], progress);
    }

    /** EXIT keyframes already carry TAA's (t - 0.24) / 0.76 sample-time remap. */
    public Frame exit(boolean gun, double progress) {
        return interpolate(exit[variant(gun)], progress);
    }

    /**
     * Bound on {@link LocalObb#reach} of every box {@link ProneLayouts#resolve} builds from this
     * table. Blends with weights in [0, 1] that sum to 1 stay within their inputs; a transition adds
     * at most one whole {@code steady(aim, pitch) - steady(0, 0)} offset to an interpolated keyframe.
     */
    public double reachBound() {
        return reachBound;
    }

    private double computeReachBound() {
        double bound = 0.0D;
        for (boolean gun : new boolean[]{true, false}) {
            bound = Math.max(bound, crawlEnvelope(gun).reach());
            BodyLayout neutral = steady(gun, 0.0D, 0.0D);
            for (SegmentId id : SegmentId.values()) {
                LocalObb zero = neutral.get(id);
                double lying = 0.0D;
                double offset = 0.0D;
                double growU = 0.0D;
                double growV = 0.0D;
                double growW = 0.0D;
                for (BodyLayout[] row : steady[variant(gun)]) {
                    for (BodyLayout layout : row) {
                        LocalObb box = layout.get(id);
                        lying = Math.max(lying, box.reach());
                        offset = Math.max(offset, box.c().distanceTo(zero.c()));
                        growU = Math.max(growU, box.u().length() - zero.u().length());
                        growV = Math.max(growV, box.v().length() - zero.v().length());
                        growW = Math.max(growW, box.w().length() - zero.w().length());
                    }
                }
                double keyframe = 0.0D;
                for (Frame[] frames : new Frame[][]{enter[variant(gun)], exit[variant(gun)]}) {
                    for (Frame frame : frames) {
                        keyframe = Math.max(keyframe, frame.layout().get(id).reach());
                    }
                }
                bound = Math.max(bound, Math.max(lying, keyframe + offset + growU + growV + growW));
            }
        }
        return bound;
    }

    BodyLayout grid(boolean gun, int aimIndex, int pitchIndex) {
        return steady[variant(gun)][aimIndex][pitchIndex];
    }

    Frame enterFrame(boolean gun, int index) {
        return enter[variant(gun)][index];
    }

    Frame exitFrame(boolean gun, int index) {
        return exit[variant(gun)][index];
    }

    private static Frame interpolate(Frame[] frames, double progress) {
        double clamped = progress >= 0.0D ? Math.min(progress, 1.0D) : 0.0D;
        double k = clamped * (FRAME_COUNT - 1);
        int i = Math.min((int) Math.floor(k), FRAME_COUNT - 2);
        double a = k - i;
        if (a <= 0.0D) {
            return frames[i];
        }
        if (a >= 1.0D) {
            return frames[i + 1];
        }
        Frame from = frames[i];
        Frame to = frames[i + 1];
        return new Frame(from.prone() + (to.prone() - from.prone()) * a,
                BodyLayout.blend(new BodyLayout[]{from.layout(), to.layout()}, new double[]{1.0D - a, a}));
    }

    private static int variant(boolean gun) {
        return gun ? GUN : EMPTY;
    }

    static String steadyKey(int aimIndex, int pitchIndex) {
        return "aim" + (aimIndex * AIM_STEP - 180) + "_pitch" + (int) PITCHES[pitchIndex];
    }

    private static Frame[] frames(JsonArray json, String path) throws IOException {
        if (json.size() != FRAME_COUNT) {
            throw new IOException(path + " needs " + FRAME_COUNT + " keyframes, got " + json.size());
        }
        Frame[] out = new Frame[FRAME_COUNT];
        for (int k = 0; k < FRAME_COUNT; k++) {
            String at = path + "[" + k + "]";
            JsonObject frame = object(json.get(k), at);
            double progress = number(frame, "progress", at);
            if (Math.abs(progress - (double) k / (FRAME_COUNT - 1)) > 1.0E-6D) {
                throw new IOException(at + " has progress " + progress + ", expected " + k + "/" + (FRAME_COUNT - 1));
            }
            double prone = number(frame, "prone", at);
            if (prone < 0.0D || prone > 1.0D) {
                throw new IOException(at + " has prone " + prone + " outside [0, 1]");
            }
            out[k] = new Frame(prone, layout(object(frame, "obb"), at + ".obb"));
        }
        return out;
    }

    private static BodyLayout layout(JsonObject json, String path) throws IOException {
        LocalObb[] boxes = new LocalObb[SegmentId.values().length];
        for (SegmentId id : SegmentId.values()) {
            String at = path + "." + id.jsonKey();
            JsonObject box = object(json, id.jsonKey());
            boxes[id.ordinal()] = new LocalObb(
                    vector(box, "c", at), vector(box, "u", at), vector(box, "v", at), vector(box, "w", at))
                    .orthonormalized();
        }
        return new BodyLayout(boxes);
    }

    private static BodyLayout extentsLayout(JsonObject json, String path) throws IOException {
        LocalObb[] boxes = new LocalObb[SegmentId.values().length];
        for (SegmentId id : SegmentId.values()) {
            String at = path + "." + id.jsonKey();
            JsonObject box = object(json, id.jsonKey());
            double[] f = range(box, "f", at);
            double[] s = range(box, "s", at);
            double[] y = range(box, "y", at);
            boxes[id.ordinal()] = LocalObb.ofExtents(f[0], f[1], s[0], s[1], y[0], y[1]);
        }
        return new BodyLayout(boxes);
    }

    private static Vec3 vector(JsonObject json, String key, String path) throws IOException {
        double[] xyz = numbers(array(json, key), 3, path + "." + key);
        return new Vec3(xyz[0], xyz[1], xyz[2]);
    }

    private static double[] range(JsonObject json, String key, String path) throws IOException {
        double[] range = numbers(array(json, key), 2, path + "." + key);
        if (!(range[1] > range[0])) {
            throw new IOException(path + "." + key + " is empty: " + range[0] + ".." + range[1]);
        }
        return range;
    }

    private static double[] numbers(JsonArray json, int count, String path) throws IOException {
        if (json.size() != count) {
            throw new IOException(path + " needs " + count + " numbers, got " + json.size());
        }
        double[] out = new double[count];
        for (int i = 0; i < count; i++) {
            out[i] = finite(json.get(i).getAsDouble(), path + "[" + i + "]");
        }
        return out;
    }

    private static double number(JsonObject json, String key, String path) throws IOException {
        JsonElement element = json.get(key);
        if (element == null || !element.isJsonPrimitive()) {
            throw new IOException(path + "." + key + " is missing");
        }
        return finite(element.getAsDouble(), path + "." + key);
    }

    private static double finite(double value, String path) throws IOException {
        if (!Double.isFinite(value)) {
            throw new IOException(path + " is not finite");
        }
        return value;
    }

    private static JsonObject object(JsonObject parent, String key) throws IOException {
        return object(parent.get(key), key);
    }

    private static JsonObject object(JsonElement element, String path) throws IOException {
        if (element == null || !element.isJsonObject()) {
            throw new IOException(path + " is missing or not an object");
        }
        return element.getAsJsonObject();
    }

    private static JsonArray array(JsonObject parent, String key) throws IOException {
        JsonElement element = parent.get(key);
        if (element == null || !element.isJsonArray()) {
            throw new IOException(key + " is missing or not an array");
        }
        return element.getAsJsonArray();
    }
}
