package com.wok.infantry.client.screen;

import com.mojang.blaze3d.systems.RenderSystem;
import com.wok.infantry.WokInfantryMod;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.resources.ResourceLocation;

/**
 * The tactical-tablet GUI textures and the blit helpers that draw them.
 *
 * <p>All three sheets are generated by {@code ui-preview/tools/export-ui-atlas.mjs} from the
 * layout preview's own pixel art ({@code kit/icons.js}, {@code kit/map-icons.js}); they are
 * original art, not third-party assets. Re-run the script instead of editing the PNGs: the
 * atlas tests compare them with the generated manifest.
 *
 * <p>{@link GuiGraphics#blit} draws immediately while fills and text may still sit in a
 * managed batch, so every helper flushes first; a blit therefore always lands above whatever
 * was drawn before it.
 */
public final class TacticalTextures {
    /** 9×9 monochrome UI icons on a 10px pitch, 16 per row (see {@link TacticalIcon}). */
    public static final ResourceLocation UI_ICONS = ResourceLocation.fromNamespaceAndPath(
            WokInfantryMod.MOD_ID, "textures/gui/ui_icons.png");
    public static final int UI_ICONS_WIDTH = 256;
    public static final int UI_ICONS_HEIGHT = 64;

    /** 4×4 tile of the disabled-key hatch; not clamped, so one blit tiles it by UV wrap-around. */
    public static final ResourceLocation UI_HATCH = ResourceLocation.fromNamespaceAndPath(
            WokInfantryMod.MOD_ID, "textures/gui/ui_hatch.png");
    public static final int UI_HATCH_SIZE = 4;

    /** Map marker layers: plates, edges with shadow, rings and silhouettes in 24px cells. */
    public static final ResourceLocation MAP_ICONS = ResourceLocation.fromNamespaceAndPath(
            WokInfantryMod.MOD_ID, "textures/gui/map_icons.png");
    public static final int MAP_ICONS_SIZE = 128;

    private TacticalTextures() {
    }

    /**
     * Draws a texture region into [x, x + width) × [y, y + height), multiplied by {@code argb}
     * (white texels take exactly that colour; its alpha fades the whole region).
     */
    public static void blitTinted(GuiGraphics graphics, ResourceLocation texture, int x, int y,
                                  int width, int height, float u, float v, int regionWidth,
                                  int regionHeight, int textureWidth, int textureHeight,
                                  int argb) {
        if (width <= 0 || height <= 0 || (argb >>> 24) == 0) {
            return;
        }
        begin(graphics);
        tint(graphics, argb, 1.0F);
        graphics.blit(texture, x, y, width, height, u, v, regionWidth, regionHeight,
                textureWidth, textureHeight);
        end(graphics);
    }

    /**
     * Tiles a repeating texture over [left, right) × [top, bottom) in one blit, one texel per
     * GUI unit, with texel (0, 0) at the region's top-left corner.
     */
    public static void tile(GuiGraphics graphics, ResourceLocation texture, int left, int top,
                            int right, int bottom, int textureWidth, int textureHeight) {
        if (right <= left || bottom <= top) {
            return;
        }
        begin(graphics);
        graphics.blit(texture, left, top, 0.0F, 0.0F, right - left, bottom - top,
                textureWidth, textureHeight);
        end(graphics);
    }

    /**
     * Starts a run of blended blits: flushes pending batched fills and text so the blits land
     * above them, and enables standard alpha blending. Pair with {@link #end}.
     */
    public static void begin(GuiGraphics graphics) {
        graphics.flush();
        RenderSystem.enableBlend();
        RenderSystem.defaultBlendFunc();
    }

    /** Sets the shader colour for the next blits: {@code argb} with its alpha times {@code alpha}. */
    public static void tint(GuiGraphics graphics, int argb, float alpha) {
        float[] rgba = rgba(argb, alpha);
        graphics.setColor(rgba[0], rgba[1], rgba[2], rgba[3]);
    }

    /** Ends a run started with {@link #begin}: resets the shader colour and disables blending. */
    public static void end(GuiGraphics graphics) {
        graphics.setColor(1.0F, 1.0F, 1.0F, 1.0F);
        RenderSystem.disableBlend();
    }

    /** Shader colour components of {@code argb}, its alpha multiplied by {@code alpha} (0–1). */
    public static float[] rgba(int argb, float alpha) {
        float fade = Float.isFinite(alpha) ? Math.max(0.0F, Math.min(1.0F, alpha)) : 0.0F;
        return new float[]{
                ((argb >>> 16) & 0xFF) / 255.0F,
                ((argb >>> 8) & 0xFF) / 255.0F,
                (argb & 0xFF) / 255.0F,
                ((argb >>> 24) & 0xFF) / 255.0F * fade
        };
    }
}
