package com.wok.infantry.client.screen;

import java.util.Map;

import static com.wok.infantry.client.screen.PaletteToken.*;
import static java.util.Map.entry;

/**
 * P3 screen-palette overrides of each faction livery, on top of the A scheme (preview
 * {@code ui-preview/surfaces/18-device-livery.js}: {@code INNER.<livery>} with {@code SHARED}
 * spread in, and the page scope {@code SCOPE.map.caesar}). The preview's {@code WELL_LIP} is
 * {@link PaletteToken#WELL_LIGHT_EDGE}.
 *
 * <p>Generated, not hand-copied: the tables are the output of
 * {@code node tools/export-palette.mjs --java} (run in {@code ui-preview}). After a preview colour
 * change, re-export {@code src/test/resources/ui_palette/p3_palette.json} with
 * {@code --module <wok_infantry>} and paste the new tables; {@code TacticalPaletteTest} compares
 * every value of every livery with that file. {@link TacticalPalette} adds the derived tokens.
 */
final class TacticalLiveryTables {
    /** INNER.academy (SHARED included). */
    static final Map<PaletteToken, Integer> ACADEMY = Map.ofEntries(
            entry(ON_FILL, 0xFFF6F8F7),
            entry(SUCCESS_EDGE, 0xFF285640),
            entry(DISABLED_EDGE, 0xFF7E8898),
            entry(SUCCESS, 0xFF36704F),
            entry(SUCCESS_HOVER, 0xFF3B7A57),
            entry(ACCENT_TEXT, 0xFF844600),
            entry(FRAME, 0xFF0A162D),
            entry(FRAME_MID, 0xFF19325D),
            entry(RIVET, 0xFF040A18),
            entry(BOARD, 0xFFB2C1D4),
            entry(BOARD_ALT, 0xFFCAD5E2),
            entry(CARD, 0xFFDCE5EF),
            entry(CARD_HOVER, 0xFFE8EEF6),
            entry(CARD_PRESSED, 0xFFC8D3E1),
            entry(CARD_DISABLED, 0xFFA7B2BF),
            entry(CARD_LIP, 0xFFB9C7D7),
            entry(BEVEL, 0xFFF5F8FC),
            entry(BADGE_BG, 0xFFDCE5EF),
            entry(WELL, 0xFF0C1D3B),
            entry(WELL_ROW, 0xFF132A50),
            entry(WELL_ROW_ALT, 0xFF12274C),
            entry(ROW_HOVER, 0xFF22416F),
            entry(WELL_EDGE, 0xFF2E4B7A),
            entry(WELL_LIGHT_EDGE, 0xFF2C4A78),
            entry(CELL, 0xFF2A4166),
            entry(CELL_EDGE, 0xFF4A6690),
            entry(INPUT_EDGE, 0xFF4A6690),
            entry(BORDER, 0xFF42587C),
            entry(BORDER_DARK, 0xFF22344F),
            entry(EDGE, 0x40182A48),
            entry(TEXT, 0xFF101C30),
            entry(MUTED, 0xFF3D4F6B),
            entry(FAINT, 0xFF627694),
            entry(LIGHT, 0xFFEEF4FA),
            entry(LIGHT_MUTED, 0xFFA2B6D0),
            entry(OFFLINE, 0xFF7D8BA0),
            entry(DISABLED_TEXT, 0xFF46525F),
            entry(DANGER, 0xFFA63A32),
            entry(DANGER_HOVER, 0xFFB8463D),
            entry(DANGER_B, 0xFFFF8070),
            entry(ACCENT, 0xFFA45F0E),
            entry(ADJUST, 0xFFA45F0E),
            entry(SELECT, 0xFF2660A8),
            entry(SELECT_HOVER, 0xFF3272BA),
            entry(SELECT_EDGE, 0xFF173F75),
            entry(SELECT_BAR, 0xFFB8DCFA),
            entry(SELECT_B, 0xFF8AC4F5),
            entry(SELECT_SUB, 0xFFEEF6FE),
            entry(ON_SELECT, 0xFFFFFFFF),
            entry(SELECT_WELL, 0xFF1C3A63),
            entry(DANGER_DEEP, 0xFF3A0F0C),
            entry(HUD_TRACK, 0xCC3B5277),
            entry(FOCUS, 0xFFF4F8FC));

    /** INNER.caesar (SHARED included). */
    static final Map<PaletteToken, Integer> CAESAR = Map.ofEntries(
            entry(ON_FILL, 0xFFF6F8F7),
            entry(SUCCESS_EDGE, 0xFF285640),
            entry(DISABLED_EDGE, 0xFF8E8685),
            entry(SUCCESS, 0xFF36704F),
            entry(SUCCESS_HOVER, 0xFF3B7A57),
            entry(ACCENT_TEXT, 0xFF844600),
            entry(FRAME, 0xFF26090C),
            entry(FRAME_MID, 0xFF64161D),
            entry(RIVET, 0xFF160406),
            entry(BOARD, 0xFFC6BBB9),
            entry(BOARD_ALT, 0xFFD6CDCB),
            entry(CARD, 0xFFEBE5E3),
            entry(CARD_HOVER, 0xFFF5F1F0),
            entry(CARD_PRESSED, 0xFFDDD5D3),
            entry(CARD_DISABLED, 0xFFB8B0AF),
            entry(CARD_LIP, 0xFFD3CAC8),
            entry(BEVEL, 0xFFFCFAF9),
            entry(BADGE_BG, 0xFFEBE5E3),
            entry(WELL, 0xFF350D12),
            entry(WELL_ROW, 0xFF46131A),
            entry(WELL_ROW_ALT, 0xFF401118),
            entry(ROW_HOVER, 0xFF5E1C24),
            entry(WELL_EDGE, 0xFF702830),
            entry(WELL_LIGHT_EDGE, 0xFF63212A),
            entry(CELL, 0xFF562128),
            entry(CELL_EDGE, 0xFF84434A),
            entry(INPUT_EDGE, 0xFF84434A),
            entry(BORDER, 0xFF6E3438),
            entry(BORDER_DARK, 0xFF451A1E),
            entry(EDGE, 0x40501A20),
            entry(TEXT, 0xFF2A0F12),
            entry(MUTED, 0xFF5E3E40),
            entry(FAINT, 0xFF846A6C),
            entry(LIGHT, 0xFFFAF1EF),
            entry(LIGHT_MUTED, 0xFFD4BAB7),
            entry(OFFLINE, 0xFF957F80),
            entry(DISABLED_TEXT, 0xFF5A504F),
            entry(SELECT, 0xFF8E1A34),
            entry(SELECT_HOVER, 0xFFAA2642),
            entry(SELECT_EDGE, 0xFF48081A),
            entry(SELECT_BAR, 0xFFFFE6E0),
            entry(SELECT_B, 0xFFFF9EB4),
            entry(SELECT_SUB, 0xFFFCE0DC),
            entry(ON_SELECT, 0xFFFFF8F6),
            entry(SELECT_WELL, 0xFF5E1622),
            entry(DANGER, 0xFFB63A1C),
            entry(DANGER_HOVER, 0xFFC04424),
            entry(DANGER_B, 0xFFFF6E4A),
            entry(DANGER_DEEP, 0xFF2A0606),
            entry(ACCENT, 0xFFA45F0E),
            entry(ADJUST, 0xFFA45F0E),
            entry(HUD_TRACK, 0xCC5E2730),
            entry(FOCUS, 0xFFFFF4F2));

    /** SCOPE.map.caesar, on top of CAESAR. */
    static final Map<PaletteToken, Integer> CAESAR_MAP = Map.ofEntries(
            entry(SELECT, 0xFF3B4247),
            entry(SELECT_HOVER, 0xFF4B545A),
            entry(SELECT_EDGE, 0xFF1A1F22),
            entry(SELECT_BAR, 0xFFFF9EB4),
            entry(ON_SELECT, 0xFFF5F7F8),
            entry(SELECT_SUB, 0xFFCBD3D7),
            entry(SELECT_WELL, 0xFF2A3034));

    /** INNER.neutral (SHARED included). */
    static final Map<PaletteToken, Integer> NEUTRAL = Map.ofEntries(
            entry(ON_FILL, 0xFFF6F8F7),
            entry(SUCCESS_EDGE, 0xFF285640),
            entry(DISABLED_EDGE, 0xFF959DA0),
            entry(SUCCESS, 0xFF36704F),
            entry(SUCCESS_HOVER, 0xFF3B7A57),
            entry(ACCENT_TEXT, 0xFF844600),
            entry(FRAME, 0xFFAEB7BA),
            entry(FRAME_MID, 0xFFADB7BB),
            entry(RIVET, 0xFF7D878A),
            entry(BOARD, 0xFFD8DDDE),
            entry(BOARD_ALT, 0xFFCBD1D3),
            entry(CARD, 0xFFF2F4F4),
            entry(CARD_HOVER, 0xFFFAFBFB),
            entry(CARD_PRESSED, 0xFFE2E7E7),
            entry(CARD_DISABLED, 0xFFC6CCCD),
            entry(CARD_LIP, 0xFFD6DCDC),
            entry(BEVEL, 0xFFFFFFFF),
            entry(BADGE_BG, 0xFFF2F4F4),
            entry(WELL, 0xFFE6EAEB),
            entry(WELL_ROW, 0xFFEEF1F2),
            entry(WELL_ROW_ALT, 0xFFE8ECED),
            entry(ROW_HOVER, 0xFFDCE3E6),
            entry(WELL_EDGE, 0xFFAAB3B6),
            entry(WELL_LIGHT_EDGE, 0xFFF7F9F9),
            entry(CELL, 0xFF9AA4A7),
            entry(CELL_EDGE, 0xFF7D878A),
            entry(INPUT_EDGE, 0xFF8A9497),
            entry(BORDER, 0xFF7D878A),
            entry(BORDER_DARK, 0xFF586366),
            entry(EDGE, 0x40303A3D),
            entry(TEXT, 0xFF1C2427),
            entry(MUTED, 0xFF4C585C),
            entry(FAINT, 0xFF687377),
            entry(LIGHT, 0xFF1C2427),
            entry(LIGHT_MUTED, 0xFF3E494D),
            entry(OFFLINE, 0xFF7F898C),
            entry(DISABLED_TEXT, 0xFF5B6568),
            entry(SELECT, 0xFF384246),
            entry(SELECT_HOVER, 0xFF465256),
            entry(SELECT_EDGE, 0xFF1E2528),
            entry(SELECT_BAR, 0xFFE6ECEE),
            entry(SELECT_B, 0xFF2F3A3E),
            entry(SELECT_SUB, 0xFFC9D2D5),
            entry(ON_SELECT, 0xFFF4F7F8),
            entry(SELECT_WELL, 0xFFCFD6D8),
            entry(DANGER_HOVER, 0xFFB84A40),
            entry(SUCCESS_B, 0xFF1F6236),
            entry(DANGER_B, 0xFFA02C22),
            entry(NEUTRAL_B, 0xFF56636A),
            entry(ACCENT, 0xFF9C4600),
            entry(ACCENT_B, 0xFF9C4600),
            entry(SECTION, 0xFF9C4600),
            entry(SECTION_B, 0xFF9C4600),
            entry(ADJUST, 0xFF9C4600),
            entry(ADJUST_B, 0xFF9C4600),
            entry(DANGER_DEEP, 0xFF3A0F0C),
            entry(HUD_TRACK, 0xFFC3CBCD),
            entry(FOCUS, 0xFF1C2427));

    private TacticalLiveryTables() {
    }
}