/* WOK步战离线工作台。无请求、无服务器；所有导出由用户保存到本机。 */
(() => {
'use strict';
const C=window.WokCatalog,S=window.WokSnbt,$=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy=v=>JSON.parse(JSON.stringify(v));
const tabs=[['overview','编制概览'],['loadout','兵种配装'],['vehicles','载具'],['support','部署支援'],['check','检查与导出']];
const targets=[...Array.from({length:9},(_,i)=>`HOTBAR_${i+1}`),'OFFHAND','ARMOR_HEAD','ARMOR_CHEST','ARMOR_LEGS','ARMOR_FEET'];
const targetLabel=t=>t.startsWith('HOTBAR_')?'快捷栏 '+t.slice(7):({OFFHAND:'副手',ARMOR_HEAD:'头盔',ARMOR_CHEST:'胸甲',ARMOR_LEGS:'护腿',ARMOR_FEET:'靴子'}[t]||t);
const cats={infantry:'步兵',armored:'装甲',motorized:'摩步',mechanized:'机械化',special:'特种'};
const tuning=[['ads_speed','开镜速度','数值越大，开镜越快'],['vertical_recoil','垂直后坐力','数值越大，后坐越强'],['horizontal_recoil','水平后坐力','数值越大，后坐越强'],['spread','散布','数值越大，散布越大'],['damage','伤害','原始伤害 × 此倍率'],['armor_ignore','穿甲','原始穿甲比例 × 倍率，上限 100%'],['rpm','射速','原始射速 × 此倍率']];
let state={catalog:copy(window.WOK_EDITOR_SEED.catalog),base:copy(window.WOK_EDITOR_SEED.catalog),source:window.WOK_EDITOR_SEED.source,kind:'seed',dirty:false,tab:'loadout',factionId:'academy',formationId:'millennium_seminar_mobile',classId:'',slotId:'',entryId:''};
let undo=[],bindings=[],fileMode='open',savedTimer=null,modalAction=null,libraryMode='entries';
const bank=window.WOK_RESOURCE_BANK||{entries:[],guns:[],attachments:[],vehicles:[]};
function faction(){return state.catalog.formations.factions.find(f=>f.id===state.factionId)||state.catalog.formations.factions[0]}
function formation(){const f=faction();return f?.formations.find(f=>f.id===state.formationId)||f?.formations[0]}
function rule(){return formation()?.classes.find(r=>r.classId===state.classId)||formation()?.classes[0]}
function role(){return state.catalog.loadouts.classes.find(r=>r.id===rule()?.classId)}
function slot(){return role()?.slotDefinitions.find(s=>s.id===state.slotId)||role()?.slotDefinitions[0]}
function entries(){return role()?.slots[slot()?.id]||[]}
function entry(){return entries().find(e=>e.id===state.entryId)||entries()[0]}
function normalizeSelection(){state.factionId=faction()?.id||'';state.formationId=formation()?.id||'';state.classId=rule()?.classId||'';state.slotId=slot()?.id||'';state.entryId=entry()?.id||'';}
function message(text){$('status').textContent=text}
function project(){return{format:'wok_infantry_editor_project',version:1,savedAt:new Date().toISOString(),sourceName:state.source,base:state.base,catalog:state.catalog}}
function autosave(){clearTimeout(savedTimer);savedTimer=setTimeout(()=>{try{localStorage.setItem('wok-infantry-editor-v1',JSON.stringify(project()));message('草稿已保存在此浏览器 · 请保存工程文件用于交付')}catch{message('浏览器不能保存草稿，请使用“保存工程”下载文件')}},250)}
function mutate(label,fn){const before=copy({catalog:state.catalog,base:state.base,source:state.source,kind:state.kind});try{fn();undo.push(before);if(undo.length>50)undo.shift();state.dirty=true;normalizeSelection();render();message(label);autosave()}catch(e){Object.assign(state,before);render();throw e}}
function showError(msg){showModal('需要修正',`<p class="error-text">${esc(msg)}</p><div class="actions"><button data-action="close-modal">返回编辑</button></div>`)}
function bind(obj,key,opts={}){return custom(obj[key],v=>{obj[key]=v},opts)}
function custom(value,fn,opts={}){const id=bindings.push({fn,type:opts.type||'text'})-1;let attrs=`data-bind="${id}" aria-label="${esc(opts.label||'编辑值')}"`;
 if(opts.readonly)attrs+=' readonly';if(opts.maxlength)attrs+=` maxlength="${opts.maxlength}"`;
 if(opts.type==='checkbox')return `<label class="check-option"><input type="checkbox" ${attrs} ${value?'checked':''}>${esc(opts.label)}</label>`;
 if(opts.type==='select')return `<select ${attrs}>${opts.options.map(v=>{const [a,b]=Array.isArray(v)?v:[v,v];return`<option value="${esc(a)}" ${a===value?'selected':''}>${esc(b)}</option>`}).join('')}</select>`;
 if(opts.type==='textarea')return `<textarea ${attrs} class="${opts.mono?'mono':''}" ${opts.rows?`rows="${opts.rows}"`:''}>${esc(value)}</textarea>`;
 return `<input ${attrs} type="${opts.type||'text'}" value="${esc(value)}" ${opts.min!==undefined?`min="${esc(opts.min)}"`:''} ${opts.max!==undefined?`max="${esc(opts.max)}"`:''} ${opts.step?`step="${esc(opts.step)}"`:''} ${opts.list?`list="${esc(opts.list)}"`:''}>`;
}
function field(label,control,wide=false){return `<label class="field ${wide?'wide':''}"><span>${esc(label)}</span>${control}</label>`}
function input(obj,key,label,opts={}){return field(label,bind(obj,key,{label,...opts}),opts.wide)}
const num=(obj,key,label,min,max)=>input(obj,key,label,{type:'number',min,max});
const button=(action,text,cls='',args='')=>`<button data-action="${action}" class="${cls}" ${args}>${text}</button>`;
const heading=(title,tools='')=>`<div class="section-head"><h2>${esc(title)}</h2><div class="row">${tools}</div></div>`;
function readSnbt(e,key,fallback){try{return S.readScalar(e.snbt||'{}',key,fallback)}catch{return fallback}}
function report(){const r=C.validate(state.catalog);for(const c of state.catalog.loadouts.classes||[])for(const sd of c.slotDefinitions||[])for(const e of c.slots[sd.id]||[]){if(!e.snbt)continue;try{S.parse(e.snbt);for(const [tag]of tuning){const v=S.readScalar(e.snbt,'wok_infantry_'+tag+'_scale',1);if(typeof v!=='number'||!Number.isFinite(v)||v<.25||v>15)r.errors.push(`${c.displayName} / ${e.displayName}：${tag} 倍率须为 0.25–15`)}if(e.itemId==='tacz:modern_kinetic_gun'&&!S.readGunId(e.snbt))r.errors.push(`${e.displayName}：缺少 GunId`)}catch(err){r.errors.push(`${c.displayName} / ${e.displayName}：${err.message}`)}}
 for(const c of state.catalog.loadouts.classes||[])for(const sd of c.slotDefinitions||[])for(const e of c.slots[sd.id]||[])if(e.itemId==='tacz:modern_kinetic_gun'&&!e.snbt)r.errors.push(`${e.displayName}：枪械缺少 GunId 与状态数据`);
 for(const c of state.catalog.loadouts.classes||[])for(const sd of c.slotDefinitions||[])for(const e of c.slots[sd.id]||[]){if(e.itemId!=='tacz:modern_kinetic_gun')continue;try{const text=e.snbt||'{}',gun=S.readGunId(text);const resource=/^[a-z0-9_.-]+:[a-z0-9_./-]+$/;if(typeof gun!=='string'||!resource.test(gun))r.errors.push(e.displayName+'：GunId 必须是有效资源 ID 字符串');else if(!bank.guns.some(g=>g.id===gun))r.warnings.push(e.displayName+'：此枪型不在随包资源库，请核对目标环境');for(const t of S.ATTACHMENT_SLOTS){const a=S.readAttachment(text,t);if(a&&(typeof a!=='string'||!resource.test(a)))r.errors.push(e.displayName+'：'+t+' 配件 ID 无效')}const ammo=S.readScalar(text,'GunCurrentAmmoCount',0),mode=S.readScalar(text,'GunFireMode','SEMI');if(!Number.isInteger(ammo)||ammo<0)r.errors.push(e.displayName+'：弹匣当前载弹须为非负整数');if(!['SEMI','AUTO','BURST'].includes(mode))r.errors.push(e.displayName+'：开火模式无效');}catch(err){r.errors.push(e.displayName+'：'+err.message)}}
 return r;}
function render(){const opened=new Map([...document.querySelectorAll('#content details')].map(d=>[d.querySelector('summary')?.textContent,d.open]));normalizeSelection();bindings=[];const f=faction(),fm=formation();$('undo').disabled=!undo.length;
 $('sidebar').innerHTML=`<p class="eyebrow">FACTION / FORMATION</p><label class="field"><span>公开阵营</span><select id="faction-picker" aria-label="公开阵营">${state.catalog.formations.factions.map(x=>`<option value="${esc(x.id)}" ${x.id===f?.id?'selected':''}>${esc(x.displayName)} · ${x.battleSide==='blue'?'蓝方':'红方'}</option>`).join('')}</select></label><h2>作战编制 / ${f?.formations.length||0}</h2><div class="formations">${(f?.formations||[]).map(x=>`<button class="formation-card ${x===fm?'selected':''}" data-action="formation" data-id="${esc(x.id)}"><strong>${esc(x.displayName)}</strong><small>${esc(cats[x.category]||x.category)} · ${esc(x.capacity)} 人 · ${x.enabled?'启用':'停用'}</small></button>`).join('')}</div><div class="sidebar-actions">${button('clone-formation','＋ 新编制')}${button('new-faction','＋ 阵营','',''+(state.catalog.formations.factions.length>=2?'disabled':''))}</div><p class="source">编辑基线<b>${esc(state.source)}</b><br>${state.kind==='seed'?'随包配置副本。正式编辑前，可打开游戏刚导出的数据包。':'打开的是文件副本，修改仅保存在当前工作台。'}</p>`;
 $('context').innerHTML=`<p class="eyebrow">TACTICAL CONFIGURATION TERMINAL</p><h1>${esc(fm?.displayName||'新建你的作战编制')}</h1><div class="meta"><span>${esc(f?.displayName||'无阵营')}</span><span> / </span><span>${esc(fm?.id||'')}</span>${fm?`<span class="tag">${fm.classes.length} 兵种</span><span class="tag">${fm.vehicles.length} 载具</span>`:''}<span class="tag">${state.dirty?'草稿已修改':'基线已载入'}</span></div>${state.source.includes('演示目录')?'<div class="notice" style="margin:12px 0 0">当前为两套编制的演示目录。正式编辑请先打开游戏刚导出的完整数据包。</div>':''}`;
 $('tabs').innerHTML=tabs.map(([id,label])=>button('tab',label,id===state.tab?'active':'',`data-tab="${id}"`)).join('');
 if(!fm&&state.tab!=='check')$('content').innerHTML=`<div class="empty">此阵营暂无编制。${button('clone-formation','新建编制')}</div>`;
 else $('content').innerHTML=({overview:renderOverview,loadout:renderLoadout,vehicles:renderVehicles,support:renderSupport,check:renderCheck}[state.tab]||renderOverview)();
 for(const d of document.querySelectorAll('#content details')){const key=d.querySelector('summary')?.textContent;if(opened.has(key))d.open=opened.get(key)}
}
function renderOverview(){const f=faction(),fm=formation();return `<section class="panel">${heading('公开阵营')}<div class="fields">${input(f,'displayName','阵营名称',{maxlength:40})}${input(f,'id','阵营 ID',{readonly:true})}${num(f,'maxPlayers','阵营人数上限',1,40)}${field('战斗侧',bind(f,'battleSide',{label:'战斗侧',type:'select',options:[['blue','蓝方'],['red','红方']]}))}${input(f,'description','阵营简介',{type:'textarea',wide:true,maxlength:512})}${bind(f,'enabled',{type:'checkbox',label:'启用公开阵营'})}</div></section><section class="panel">${heading('当前编制',button('clone-formation','复制为独立新编制','small'))}<div class="fields">${input(fm,'displayName','编制名称',{maxlength:40})}${input(fm,'id','编制 ID',{readonly:true})}${field('类别',bind(fm,'category',{type:'select',label:'编制类别',options:Object.entries(cats)}))}${num(fm,'capacity','编制人数上限',1,f.maxPlayers)}${input(fm,'description','编制简介',{type:'textarea',wide:true,maxlength:512})}${input(fm,'icon','徽标纹理资源 ID',{wide:true})}${bind(fm,'enabled',{type:'checkbox',label:'启用当前编制'})}</div><p class="hint">复制编制会建立独立兵种装备池，之后修改不会影响来源编制。</p></section><section class="panel">${heading('小队安排',button('add-squad','＋ 小队','small'))}${fm.squads.map((q,i)=>`<div class="fields three" style="margin-bottom:12px">${input(q,'displayName',q.callsign+' / 小队名称',{maxlength:40})}${num(q,'capacity','人数',1,8)}<div class="row">${button('remove-squad','移除小队','small danger',`data-index="${i}"`)}</div></div>`).join('')}<p class="hint">最多 5 个小队，每队 1–8 人。各兵种在每队的名额，进入“兵种配装”设置。</p></section><div class="danger-zone">${button('delete-formation','删除当前编制','danger')}${button('delete-faction','删除当前阵营','danger')}</div>`;}
function uses(id){const a=[];for(const f of state.catalog.formations.factions)for(const fm of f.formations)if(fm.classes.some(x=>x.classId===id))a.push(`${f.displayName} / ${fm.displayName}`);return a;}
function staleRules(c,r){return Object.entries(r.allowedEntries).flatMap(([id,allowed])=>{if(!c.slotDefinitions.some(s=>s.id===id))return ['不存在的槽位 '+id];return allowed.filter(e=>!(c.slots[id]||[]).some(x=>x.id===e)).map(e=>id+' / '+e)})}
function renderLoadout(){const fm=formation(),r=rule(),c=role(),sd=slot(),e=entry();let html=`${heading('兵种与装备池',button('new-role','＋ 新兵种','small')+button('copy-role','复制兵种','small',!c?'disabled':''))}<div class="rolebar">${fm.classes.map(rr=>{const cc=state.catalog.loadouts.classes.find(x=>x.id===rr.classId);return button('role',esc(rr.displayName||cc?.displayName||rr.classId),rr===r?'selected':'',`data-id="${esc(rr.classId)}"`)}).join('')}</div>`;
 if(!c)return html+`<div class="empty">${r?'此兵种引用的装备池不存在。可移除失效兵种后重新创建。':'添加一个兵种开始设计配装。'}${r?button('remove-role','移除失效兵种','small danger'):''}</div>`;
 const shared=uses(c.id);if(shared.length>1)html+=`<div class="notice">此装备池被 ${shared.length} 个编制共用：${esc(shared.join('、'))}。${button('detach-role','为当前编制建立独立副本','small')}</div>`;
 const stale=staleRules(c,r);if(stale.length)html+=`<div class="notice bad">此兵种有失效的可选范围：${esc(stale.join('；'))}。${button('repair-whitelist','整理失效引用','small')}</div>`;
 html+=`<section class="panel"><div class="fields three">${input(r,'displayName','当前编制显示名称',{maxlength:40})}${input(c,'displayName','装备池名称',{maxlength:80})}${num(r,'squadLimit','默认每队名额',1,8)}</div><details><summary>小队名额与兵种身份</summary><div class="squad-table">${fm.squads.map(q=>field(q.displayName+' / '+q.callsign,custom(q.classLimits[c.id]??r.squadLimit,v=>{q.classLimits[c.id]=v},{type:'number',min:0,max:8,label:q.callsign+'兵种名额'}))).join('')}</div><p class="hint">名额 0 表示该小队禁用此兵种；留给其他兵种的总席位也应满足小队人数。</p><div class="fields">${input(c,'id','全局兵种池 ID',{readonly:true})}${num(c,'squadLimit','装备池默认名额',1,8)}${bind(c,'enabled',{type:'checkbox',label:'启用装备池'})}</div><div class="danger-zone">${button('role-up','显示顺序上移','small')}${button('role-down','显示顺序下移','small')}${button('remove-role','移除当前编制的兵种','small danger')}</div></details></section>`;
 html+=`<div class="loadout-layout"><aside><p class="eyebrow">装备槽位 / ${c.slotDefinitions.length}</p><div class="slots">${c.slotDefinitions.map((s,i)=>button('slot',`<span class="slot-icon">${String(i+1).padStart(2,'0')}</span><span><b>${esc(s.displayName)}</b><small>${esc(targetLabel(s.target))} · ${s.required?'必需':'可空'}</small></span>`,s===sd?'slot selected':'slot',`data-id="${esc(s.id)}"`)).join('')}</div><div class="slot-tools">${button('new-slot','＋ 添加槽位','small',''+(c.slotDefinitions.length>=14?'disabled':''))}</div></aside><div>`;
 if(!sd)return html+`<div class="empty">还没有装备槽位。</div></div></div>`;
 html+=`<section class="panel">${heading(sd.displayName,button('slot-up','上移','small')+button('slot-down','下移','small'))}<div class="fields">${input(sd,'displayName','槽位名称',{maxlength:80})}${field('发放位置',bind(sd,'target',{type:'select',label:'发放位置',options:targets.map(t=>[t,targetLabel(t)])}))}${bind(sd,'required',{type:'checkbox',label:'部署时必须携带此槽装备'})}</div><p class="hint">同一槽位的多个装备选一件；同时携带的装备请放在不同槽位。</p><div class="options">${entries().map(x=>button('entry',esc(x.displayName),x===e?'selected':'',`data-id="${esc(x.id)}"`)).join('')}</div><div class="row">${button('library','＋ 成品配装','small primary')}${button('gun-add','＋ 枪械库','small')}${button('new-entry','新建装备','small')}${button('empty-entry','添加“空装备”选项','small')}</div>`;
 if(e)html+=renderEntry(e,sd,r);
 else html+=`<div class="empty" style="margin-top:14px">当前槽位没有装备。选择装备库中的成品，或新建物品。</div>`;
 html+=`<details><summary>可选范围与槽位管理</summary><p class="hint">默认允许当前槽位全部选项。限定范围时至少选择一个，空列表在游戏中代表全部允许。</p><div class="list-box">${entries().map(x=>{const allowed=r.allowedEntries[sd.id]||[];return custom(!allowed.length||allowed.includes(x.id),v=>{let next=allowed.length?[...allowed]:entries().map(y=>y.id);next=v?[...new Set([...next,x.id])]:next.filter(id=>id!==x.id);if(!next.length)throw Error('不能将全部选项取消；请添加空装备选项，或移除该槽位。');r.allowedEntries[sd.id]=next},{type:'checkbox',label:x.displayName})}).join('')}</div>${button('allow-all','允许全部装备','small')}<p class="item-id">槽位 ID：${esc(sd.id)}</p><div class="danger-zone">${button('delete-slot','删除当前槽位及装备','small danger')}</div></details></section></div></div>`;
 return html;
}
function renderEntry(e,sd,r){const gun=e.itemId==='tacz:modern_kinetic_gun';const gunId=readSnbt(e,'GunId','');let html=`<div style="border-top:1px solid #9eada4;margin-top:16px;padding-top:16px"><div class="item-header"><h3>${esc(e.displayName)}</h3><span class="tag">${gun?'枪械':'物品'} · ${esc(e.count)} 件</span></div><div class="item-id">${esc(e.id)} / ${esc(e.itemId)}</div>`;
 if(gun)html+=`<div class="gun-slab"><div><small>当前枪型</small><strong>${esc((bank.guns.find(g=>g.id===gunId)||{}).displayName||e.displayName)}</strong><small>${esc(gunId||'尚未指定枪型')}</small></div><svg viewBox="0 0 180 60" aria-hidden="true"><path fill="currentColor" d="M5 18h42l13 8h46v-8h10v8h39v-4h7v4h14v7h-49l-8 10h-17l-6-10H76l6 19H66L55 34H33L5 43z"/><path fill="currentColor" d="M76 16h28v7H76zM44 12h11v10H44z"/></svg></div>`;
 html+=`<div class="fields">${input(e,'displayName','装备名称',{maxlength:80})}${num(e,'count','发放物品数量',1,64)}${input(e,'itemId','物品注册 ID',{wide:true,maxlength:256})}${gun?num(e,'ammoReserveLimit','此枪备用弹药上限（发）',1,4096):''}</div>`;
 if(gun){html+=`<div class="fields" style="margin-top:13px">${field('枪械 GunId（高级：只修改标识）',custom(gunId,v=>{e.snbt=S.setGunId(e.snbt,v)},{label:'枪械 GunId',list:'gun-list'}),true)}<datalist id="gun-list">${bank.guns.map(g=>`<option value="${esc(g.id)}">${esc(g.displayName)}</option>`).join('')}</datalist>${field('开火模式',custom(readSnbt(e,'GunFireMode','SEMI'),v=>{e.snbt=S.setScalar(e.snbt,'GunFireMode',v)},{type:'select',label:'开火模式',options:['SEMI','AUTO','BURST']}))}${field('弹匣当前载弹',custom(readSnbt(e,'GunCurrentAmmoCount',0),v=>{e.snbt=S.setScalar(e.snbt,'GunCurrentAmmoCount',v,'int')},{type:'number',min:0,max:4096,label:'弹匣当前载弹'}))}</div><p class="hint">备弹按每把枪单独生效。直接修改 GunId 会保留原有状态与配件；换成其他枪型请使用下方“更换枪型”重建状态。</p><div class="row">${button('gun-library','更换枪型','small primary')}</div><details open><summary>枪械手感 · 与游戏四项调节一致</summary><div class="tuning-grid">${tuning.slice(0,4).map(t=>tuner(e,t)).join('')}</div></details><details><summary>伤害、穿甲与射速倍率</summary><div class="tuning-grid">${tuning.slice(4).map(t=>tuner(e,t)).join('')}</div><p class="hint">这里写入逐枪属性标签；不会改动枪包的全局定义。1.00 为原值。</p></details><details><summary>枪械配件</summary><div class="fields">${['SCOPE','MUZZLE','GRIP','STOCK','LASER','EXTENDED_MAG'].map(t=>field(({SCOPE:'瞄准镜',MUZZLE:'枪口',GRIP:'握把',STOCK:'枪托',LASER:'激光',EXTENDED_MAG:'扩容弹匣'})[t],custom((()=>{try{return S.readAttachment(e.snbt,t)}catch{return''}})(),v=>{e.snbt=S.setAttachment(e.snbt,t,v)},{label:t+'配件',list:'attachment-list'}))).join('')}</div><datalist id="attachment-list">${bank.attachments.map(a=>`<option value="${esc(a.id)}">${esc(a.displayName)}</option>`).join('')}</datalist><p class="hint">清空某项将移除此配件。只改动所填配件，保留其他标签；是否可安装需在游戏中检查。</p></details>`;}
 html+=`<details><summary>高级物品数据 / SNBT</summary>${input(e,'snbt','完整物品标签',{type:'textarea',mono:true,rows:7,maxlength:32767})}<p class="hint">可粘贴游戏管理员“读取主手”取得的完整标签。非法标签会阻止导出。</p></details><div class="row" style="margin-top:14px">${button('copy-entry','复制此装备选项','small')}${button('delete-entry','删除此选项','small danger')}</div></div>`;return html;
}
function tuner(e,[key,label,hint]){const tag='wok_infantry_'+key+'_scale',value=readSnbt(e,tag,1),fn=v=>{if(!Number.isFinite(v)||v<.25||v>15)throw Error('倍率必须在 0.25–15.00 之间');e.snbt=S.setScalar(e.snbt,tag,v,'float')};return `<div class="tuning"><header><span>${label}</span>${custom(value,fn,{type:'number',min:.25,max:15,step:.05,label:label+'倍率'})}</header>${custom(value,fn,{type:'range',min:.25,max:15,step:.05,label:label+'滑块'})}<small>${hint}</small></div>`;}
function renderVehicles(){const fm=formation();return `${heading('载具配置',button('new-vehicle','＋ 添加载具','small primary'))}<p class="hint">每张卡片是一辆独立载具；同型号多辆使用“复制”。补充时间 -1 表示战损后不可再生，0 表示无额外冷却。</p><div class="vehicle-list">${fm.vehicles.map((v,i)=>`<section class="panel">${heading(v.displayName,button('copy-vehicle','复制','small',`data-index="${i}"`))}<div class="fields">${input(v,'displayName','载具名称',{maxlength:40})}${input(v,'id','载具槽位 ID',{readonly:true})}${input(v,'entityId','实体注册 ID',{wide:true,list:'vehicle-list'})}${num(v,'replenishmentCooldownSeconds','战损补充时间（秒）',-1,86400)}${input(v,'yaw','朝向角度',{type:'number',min:0,max:359.999,step:.1})}${input(v,'offsetX','相对坐标 X',{type:'number',min:-128,max:128,step:.5})}${input(v,'offsetY','相对坐标 Y',{type:'number',min:-128,max:128,step:.5})}${input(v,'offsetZ','相对坐标 Z',{type:'number',min:-128,max:128,step:.5})}</div><div class="danger-zone">${button('delete-vehicle','移除此载具','small danger',`data-index="${i}"`)}</div></section>`).join('')}</div>${!fm.vehicles.length?'<div class="empty">当前编制没有载具。</div>':''}<datalist id="vehicle-list">${bank.vehicles.map(v=>`<option value="${esc(v.id)}">${esc(v.displayName)}</option>`).join('')}</datalist><div class="notice" style="margin-top:16px">车辆位置需要在游戏内检查，避免相互重叠。此页配置编制载具与补充规则；车体血量、装甲和运输容量由对应 MOD 配置管理。</div>`;}
function renderSupport(){const p=formation().capabilities;return `<section class="panel">${heading('指挥官支援')}<div class="fields">${field('可用支援',custom(p.support.mode,v=>{p.support.mode=v;if(v!=='allow_list')p.support.allowList=[]},{type:'select',label:'支援模式',options:[['allow_list','仅允许列表中的支援'],['all','全部已注册支援'],['none','禁用支援']]}))}${field('支援 ID 列表（每行一个）',custom(p.support.allowList.join('\n'),v=>{p.support.allowList=v.split(/\s+/).filter(Boolean)},{type:'textarea',label:'支援 ID 列表'}),true)}</div><p class="hint">列表只控制可用范围；不会改变支援技能的冷却或效果。</p></section>${['outpost','rally'].map(k=>{const d=p[k];return `<section class="panel">${heading(k==='outpost'?'兵站规则':'队包规则')}<div class="fields">${bind(d,'enabled',{type:'checkbox',label:'允许部署'})}${bind(d,'squadLeaderCanPlace',{type:'checkbox',label:'队长可以放置'})}${bind(d,'commanderCanPlace',{type:'checkbox',label:'指挥官可以放置'})}${num(d,'maxActive','最多同时存在数量',0,64)}${num(d,'maxHealth','血量',0,1000000)}</div><p class="hint">启用时数量与血量必须大于 0，且至少一个放置权限开启。${k==='rally'?'实际队包部署 CD 仍遵循游戏固定 480 秒规则。':''}</p><details><summary>策略冷却字段（实际行为以游戏实现为准）</summary><div class="fields">${num(d,'placementCooldownSeconds','放置冷却（秒）',0,86400)}${num(d,'replacementCooldownSeconds','替换冷却（秒）',0,86400)}${num(d,'destructionCooldownSeconds','摧毁冷却（秒）',0,86400)}</div></details></section>`}).join('')}<section class="panel">${heading('重生设置')}<div class="fields">${num(p.respawn,'delaySeconds','重生等待（秒，-1 继承）',-1,3600)}${field('移动重生候选载具槽位 ID（每行一个）',custom(p.respawn.mobileSpawnVehicleIds.join('\n'),v=>{p.respawn.mobileSpawnVehicleIds=v.split(/\s+/).filter(Boolean)},{type:'textarea',label:'移动重生候选'}),true)}</div><p class="hint">引用当前编制里的载具槽位 ID，不能填实体 ID；声明候选不等于已满足运行条件。</p></section>`;}
function diffSummary(){const output=[];const visit=(a,b,path)=>{if(JSON.stringify(a)===JSON.stringify(b))return;if(output.length>=120)return;if(a&&b&&!Array.isArray(a)&&!Array.isArray(b)&&typeof a==='object'&&typeof b==='object'){for(const k of new Set([...Object.keys(a),...Object.keys(b)]))visit(a[k],b[k],path?path+'.'+k:k)}else{let label=path.replace(/^formations\.factions/,'阵营').replace(/^loadouts\.classes/,'兵种池');if(Array.isArray(a)&&Array.isArray(b))output.push(`${label}：列表已修改（${a.length} → ${b.length} 项）`);else output.push(`${label}：${String(a??'无').slice(0,80)} → ${String(b??'无').slice(0,80)}`)}};visit(state.base,state.catalog,'');return output;}
function renderCheck(){const r=report(),fs=state.catalog.formations.factions,forms=fs.flatMap(f=>f.formations),classes=state.catalog.loadouts.classes;const diff=diffSummary();return `<div class="stats">${[[fs.length,'公开阵营'],[forms.length,'作战编制'],[classes.length,'兵种装备池'],[forms.reduce((n,f)=>n+f.vehicles.length,0),'载具槽位']].map(([n,t])=>`<div class="stat"><strong>${n}</strong><small>${t}</small></div>`).join('')}</div><div class="notice ${r.errors.length?'bad':'good'}"><strong>${r.errors.length?`${r.errors.length} 项需要修正`:'结构检查通过，可以导出'}</strong> · ${r.warnings.length} 项提示</div>${r.errors.length?`<section class="panel">${heading('阻止导出的问题')}<ul class="check-list">${r.errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}${r.warnings.length?`<details class="panel"><summary>查看 ${r.warnings.length} 项提示</summary><ul class="check-list">${r.warnings.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>`:''}<section class="panel">${heading('导出与交付')}<div class="row">${button('save-project','保存工程文件','primary')}${button('export','导出游戏数据包','success',r.errors.length?'disabled':'')}${button('merge','合并游戏最新配置')}</div><p class="hint">工程文件保留修改基线，适合发给我或其他工作人员接着编辑。游戏数据包包含全部阵营和配装，用于游戏管理员导入。</p><div class="notice">游戏导入会整体替换阵营与配装。多人编辑或基线过旧时，先用“合并游戏最新配置”保留未涉及的最新内容；遇到同一字段冲突会停止合并。</div><details><summary>本次修改摘要（${diff.length} 项）</summary><pre>${esc(diff.join('\n')||'当前内容与打开时的基线一致。')}</pre></details></section>${helpBody()}`;}
function helpBody(){return `<section class="panel steps">${heading('带回游戏')}<div class="step"><b>01 / 从游戏导出最新基线</b><code>/loadoutadmin export "edit_base"</code><p>管理员在服务器执行。文件位于服务器运行目录 config/wok_infantry/catalogs/edit_base.json。单人游戏对应当前游戏版本目录。</p></div><div class="step"><b>02 / 打开、编辑、交付</b><p>将基线文件在本工作台“打开文件”。编辑后保存工程发给我核对，或在检查通过后导出游戏数据包。工程文件不能直接放进游戏导入。</p></div><div class="step"><b>03 / 在游戏预览并确认导入</b><p>把数据包放回同一 catalogs 目录，再执行：</p><code>/loadoutadmin import "wok_catalog.json"</code><p>查看游戏返回的差异、备份与影响说明，再执行游戏给出的确认命令。确认令牌由游戏生成，不需要自行填写或猜测。</p></div><div class="step"><b>04 / 验证实际效果</b><p>进入兵种、配装与部署菜单，验证物品、配件、备弹、小队名额和载具生成。浏览器仅能验证配置结构与 SNBT，不能运行 Minecraft 物品注册表或试射。需要包含数据包导入功能的 WOK步战核心版本。</p></div></section>`;}
function showModal(title,body){$('modal-body').innerHTML=`<h2>${esc(title)}</h2>${body}`;if(!$('modal').open)$('modal').showModal()}
function closeModal(){$('modal').close();modalAction=null}
function confirmLocal(title,body,fn){modalAction=fn;showModal(title,`<p>${esc(body)}</p><div class="actions">${button('close-modal','取消')}${button('modal-confirm','确认','danger')}</div>`)}
function newId(prefix,ids=[]){let id;do{id=prefix+'_'+Math.random().toString(36).slice(2,10)}while(ids.includes(id));return id}
function nameModal(title,defaultName,fn){modalAction=()=>{const name=$('new-name').value.trim(),id=$('new-id').value.trim();if(!name||name.length>40)throw Error('名称需为 1–40 个字符');if(!/^[a-z0-9_.-]{1,64}$/.test(id))throw Error('ID 需为 1–64 个小写字母、数字、下划线、点或连字符');fn(name,id);closeModal()};showModal(title,`<div class="fields"><label class="field"><span>名称</span><input id="new-name" value="${esc(defaultName)}" maxlength="40"></label><label class="field"><span>稳定 ID（首次建立后保留）</span><input id="new-id" value="${newId('custom')}"></label></div><div class="actions">${button('close-modal','取消')}${button('modal-confirm','创建','primary')}</div>`)}
function allowedAdd(classId,slotId,newEntryId){const rr=rule();if(rr?.classId===classId&&rr.allowedEntries[slotId]?.length)rr.allowedEntries[slotId].push(newEntryId)}
function addEntry(original){const c=role(),sd=slot(),x=copy(original);x.id=newId('item',entries().map(e=>e.id));mutate('已添加装备选项',()=>{if(entries().length>=64)throw Error('每个槽位最多 64 个装备选项');c.slots[sd.id].push(x);allowedAdd(c.id,sd.id,x.id);state.entryId=x.id});}
function removeEntryRefs(classId,slotId,id){for(const f of state.catalog.formations.factions)for(const fm of f.formations)for(const rr of fm.classes)if(rr.classId===classId&&rr.allowedEntries[slotId]){const old=rr.allowedEntries[slotId];if(old.length===1&&old[0]===id&&role().slots[slotId].length>0)throw Error('某编制白名单仅允许此项；删除会变成允许全部。先调整该编制的可选范围。');rr.allowedEntries[slotId]=old.filter(x=>x!==id)}}
function clearPoolIfUnused(id){if(!uses(id).length)state.catalog.loadouts.classes=state.catalog.loadouts.classes.filter(x=>x.id!==id)}
function installRole(source,name,id,replace=false){const fm=formation();if(state.catalog.loadouts.classes.some(x=>x.id===id))throw Error('此兵种池 ID 已存在');const old=rule(),c=source?copy(source):{id,displayName:name,enabled:true,squadLimit:8,slots:{primary:[]},slotDefinitions:[{id:'primary',displayName:'主武器',target:'HOTBAR_1',required:false}]};c.id=id;c.displayName=name;state.catalog.loadouts.classes.push(c);const r=source?copy(old):{classId:id,displayName:name,squadLimit:8,allowedEntries:{}};r.classId=id;r.displayName=name;
 if(replace){const i=fm.classes.indexOf(old);fm.classes[i]=r;for(const q of fm.squads){if(Object.hasOwn(q.classLimits,old.classId)){q.classLimits[id]=q.classLimits[old.classId];delete q.classLimits[old.classId]}}clearPoolIfUnused(old.classId)}else{fm.classes.push(r);for(const q of fm.squads)q.classLimits[id]=Math.min(r.squadLimit,q.capacity)}state.classId=id;state.slotId='';state.entryId='';}
function newFormation(name,id){const f=faction(),current=formation();if(current){const n=C.cloneFormation(state.catalog,f.id,current.id,id,name);state.formationId=n.id;return}
 const noDeploy={enabled:false,maxActive:0,squadLeaderCanPlace:false,commanderCanPlace:false,maxHealth:0,placementCooldownSeconds:0,replacementCooldownSeconds:0,destructionCooldownSeconds:0};const n={id,displayName:name,description:'',icon:'',category:'infantry',enabled:true,capacity:8,capabilities:{outpost:copy(noDeploy),rally:copy(noDeploy),respawn:{delaySeconds:-1,mobileSpawnVehicleIds:[]},support:{mode:'none',allowList:[]}},classes:[],squads:[{callsign:'alpha',displayName:'Alpha',capacity:8,classLimits:{}}],vehicles:[]};f.formations.push(n);state.formationId=id;installRole(null,'步枪兵',newId('rifleman'));}
function exportModal(){state.tab='check';render();const r=report();if(r.errors.length){message(`请先修正 ${r.errors.length} 项问题`);return}modalAction=()=>{const filename=$('export-name').value.trim();if(!/^[\p{L}\p{N}_-][\p{L}\p{N}_.-]{0,63}$/u.test(filename)||filename.endsWith('.')||/^(con|prn|aux|nul|com[0-9]|lpt[0-9])(?:\..*)?$/i.test(filename))throw Error('文件名须为 1–64 个字母、汉字、数字、_、-、.，不能含路径');const archive=C.exportArchive(state.catalog);download(filename+'.json',archive);closeModal();message('游戏数据包已下载；按说明放入 catalogs 后在游戏预览导入')};showModal('导出游戏数据包',`<div class="notice good">配置结构检查通过。文件包含所有阵营、编制、兵种与装备。</div><label class="field"><span>数据包文件名（不含 .json）</span><input id="export-name" value="${state.source.includes('演示目录')?'wok_catalog_demo':'wok_catalog'}" maxlength="64"></label><p class="hint">基线：${esc(state.source)}。游戏按完整数据包替换；如游戏配置已被其他人修改，先关闭此窗口并合并最新基线。</p><div class="actions">${button('close-modal','返回')}${button('modal-confirm','下载数据包','success')}</div>`)}
function download(name,obj){const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)+'\n'],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function showLibrary(mode='entries'){libraryMode=mode;showModal(mode==='entries'?'从现有配装库添加':mode==='gun-add'?'从枪械库添加':'更换枪型',`<input id="library-search" aria-label="搜索装备" placeholder="搜索装备名、枪型或来源兵种…"><p class="hint">${mode==='entries'?'选择成品保留现有枪械、配件、标签和备弹上限。':'选择新枪型将使用该枪型的默认倍率、弹匣与火控状态，不安装配件。更换时会清除原枪的标签。'}</p><div id="library-results" class="library-list"></div><div class="actions">${button('close-modal','取消')}</div>`);renderLibrary('');$('library-search').focus()}
function renderLibrary(query){const q=query.toLowerCase(),list=libraryMode==='entries'?bank.entries:bank.guns;$('library-results').innerHTML=list.map((x,i)=>({x,i})).filter(({x})=>JSON.stringify(libraryMode==='entries'?[x.label,x.sourceClass,x.entry.displayName,x.entry.itemId,x.entry.snbt]:[x.id,x.displayName,x.nameZh,x.nameEn]).toLowerCase().includes(q)).slice(0,150).map(({x,i})=>button('library-pick','<span><b>'+esc(libraryMode==='entries'?(x.label||x.entry.displayName):x.displayName)+'</b><small>'+esc(libraryMode==='entries'?(x.sourceClass+' / '+x.entry.itemId):x.id)+'</small></span><span class="plus">＋</span>','',`data-index="${i}"`)).join('')||'<p class="hint">没有匹配结果。可输入精确资源 ID。</p>'}
function gunEntry(g){const modes=Array.isArray(g.fireModes)?g.fireModes.map(x=>String(x).toUpperCase()):[],mode=modes.find(x=>['SEMI','AUTO','BURST'].includes(x))||'SEMI';let snbt='{}';snbt=S.setGunId(snbt,g.id);snbt=S.setScalar(snbt,'GunCurrentAmmoCount',Number.isInteger(g.ammoAmount)&&g.ammoAmount>=0?g.ammoAmount:0,'int');snbt=S.setScalar(snbt,'GunFireMode',mode);snbt=S.setScalar(snbt,'HasBulletInBarrel',0,'byte');return {id:newId('gun'),displayName:g.displayName.slice(0,80),itemId:g.itemId||'tacz:modern_kinetic_gun',count:1,snbt,ammoReserveLimit:180}}
function reorder(list,item,step){const i=list.indexOf(item),j=i+step;if(j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]]}
const actions={
 'tab':el=>{state.tab=el.dataset.tab;render()},'formation':el=>{state.formationId=el.dataset.id;state.classId='';state.slotId='';state.entryId='';render()},'role':el=>{state.classId=el.dataset.id;state.slotId='';state.entryId='';render()},'slot':el=>{state.slotId=el.dataset.id;state.entryId='';render()},'entry':el=>{state.entryId=el.dataset.id;render()},
 'open':()=>{fileMode='open';$('file').click()},'merge':()=>{fileMode='merge';$('file').click()},'save-project':()=>{download('wok_editor_project.json',project());state.dirty=false;render();message('工程文件已下载，包含当前配置与修改基线')},'export':exportModal,'undo':()=>{if(undo.length){Object.assign(state,undo.pop());state.dirty=true;render();autosave();message('已撤销上一次修改')}},'close-modal':closeModal,'modal-confirm':()=>{if(modalAction)modalAction()},'help':()=>showModal('离线编辑与导入说明',helpBody()+`<div class="actions">${button('close-modal','知道了')}</div>`),
 'clone-formation':()=>nameModal('建立新编制',formation()?formation().displayName+' 副本':'新编制',(name,id)=>mutate('已创建独立编制',()=>newFormation(name,id))),
 'new-faction':()=>nameModal('新建公开阵营','新阵营',(name,id)=>mutate('已新建阵营',()=>{const fs=state.catalog.formations.factions;if(fs.length>=2)throw Error('当前游戏最多两个公开阵营');if(fs.some(f=>f.id===id))throw Error('阵营 ID 重复');fs.push({id,displayName:name,description:'',battleSide:fs.some(f=>f.battleSide==='blue')?'red':'blue',enabled:true,maxPlayers:40,formations:[]});state.factionId=id;state.formationId='';newFormation('常规编制','default')})),
 'delete-formation':()=>confirmLocal('删除编制',`删除“${formation().displayName}”及不再被其他编制引用的专用装备池。可撤销。`,()=>{mutate('已删除编制',()=>{const fm=formation(),ids=fm.classes.map(r=>r.classId);faction().formations=faction().formations.filter(x=>x!==fm);ids.forEach(clearPoolIfUnused)});closeModal()}),
 'delete-faction':()=>confirmLocal('删除阵营',`将删除“${faction().displayName}”的全部编制及不再被引用的装备池。`,()=>{mutate('已删除阵营',()=>{if(state.catalog.formations.factions.length<=1)throw Error('至少保留一个阵营');const f=faction(),ids=f.formations.flatMap(x=>x.classes.map(r=>r.classId));state.catalog.formations.factions=state.catalog.formations.factions.filter(x=>x!==f);ids.forEach(clearPoolIfUnused)});closeModal()}),
 'add-squad':()=>mutate('已添加小队',()=>{const fm=formation(),id=['alpha','bravo','charlie','delta','echo'].find(s=>!fm.squads.some(q=>q.callsign===s));if(!id)throw Error('最多 5 个小队');fm.squads.push({callsign:id,displayName:id[0].toUpperCase()+id.slice(1),capacity:8,classLimits:Object.fromEntries(fm.classes.map(r=>[r.classId,r.squadLimit]))})}),
 'remove-squad':el=>mutate('已移除小队',()=>formation().squads.splice(Number(el.dataset.index),1)),
 'new-role':()=>nameModal('新建兵种','步枪兵',(name,id)=>mutate('已新建兵种',()=>installRole(null,name,id))),
 'copy-role':()=>nameModal('复制兵种',role().displayName+' 副本',(name,id)=>mutate('已复制兵种与装备',()=>installRole(role(),name,id))),
 'detach-role':()=>nameModal('建立独立装备池',rule().displayName||role().displayName,(name,id)=>mutate('已为当前编制建立独立装备池',()=>installRole(role(),name,id,true))),
 'remove-role':()=>confirmLocal('移除兵种','从当前编制移除此兵种。其他编制的引用会保留。',()=>{mutate('已移除兵种',()=>{const fm=formation(),id=rule().classId;fm.classes=fm.classes.filter(r=>r.classId!==id);for(const q of fm.squads)delete q.classLimits[id];clearPoolIfUnused(id)});closeModal()}),
 'role-up':()=>mutate('已调整兵种顺序',()=>reorder(formation().classes,rule(),-1)),'role-down':()=>mutate('已调整兵种顺序',()=>reorder(formation().classes,rule(),1)),
 'new-slot':()=>nameModal('添加装备槽位','新槽位',(name,id)=>mutate('已添加槽位',()=>{const c=role(),target=targets.find(t=>!c.slotDefinitions.some(s=>s.target===t));if(!target)throw Error('全部 14 个发放位置均已使用');if(c.slotDefinitions.some(s=>s.id===id))throw Error('槽位 ID 重复');c.slotDefinitions.push({id,displayName:name,target,required:false});c.slots[id]=[];state.slotId=id})),
 'slot-up':()=>mutate('已调整槽位顺序',()=>reorder(role().slotDefinitions,slot(),-1)),'slot-down':()=>mutate('已调整槽位顺序',()=>reorder(role().slotDefinitions,slot(),1)),
 'delete-slot':()=>confirmLocal('删除槽位','删除此槽位及其中全部装备选项。使用相同装备池的编制也会同步变化。',()=>{mutate('已删除槽位',()=>{const c=role(),id=slot().id;c.slotDefinitions=c.slotDefinitions.filter(s=>s.id!==id);delete c.slots[id];for(const f of state.catalog.formations.factions)for(const fm of f.formations)for(const r of fm.classes)if(r.classId===c.id)delete r.allowedEntries[id]});closeModal()}),
 'library':()=>showLibrary('entries'),'gun-library':()=>showLibrary('gun-replace'),'gun-add':()=>showLibrary('gun-add'),'library-pick':el=>{const index=Number(el.dataset.index);if(libraryMode==='entries')addEntry(bank.entries[index].entry);else if(libraryMode==='gun-add')addEntry(gunEntry(bank.guns[index]));else mutate('已更换枪型并重建状态',()=>{const e=entry(),next=gunEntry(bank.guns[index]);next.id=e.id;next.ammoReserveLimit=e.ammoReserveLimit;Object.assign(e,next)});closeModal()},
 'new-entry':()=>addEntry({id:'new_item',displayName:'新装备',itemId:'minecraft:stone',count:1,snbt:'',ammoReserveLimit:180}),
 'empty-entry':()=>{mutate('已允许空装备并添加显式选项',()=>{const c=role(),s=slot(),id=newId('empty');if(entries().length>=64)throw Error('每槽最多 64 项');s.required=false;c.slots[s.id].push({id,displayName:'不携带装备',itemId:'minecraft:air',count:1,snbt:'',ammoReserveLimit:180});allowedAdd(c.id,s.id,id);state.entryId=id})},
 'copy-entry':()=>addEntry({...entry(),displayName:entry().displayName+' 副本'}),
 'delete-entry':()=>mutate('已删除装备选项',()=>{const c=role(),s=slot(),id=entry().id;c.slots[s.id]=entries().filter(e=>e.id!==id);removeEntryRefs(c.id,s.id,id)}),
 'allow-all':()=>mutate('当前编制允许该槽全部装备',()=>{delete rule().allowedEntries[slot().id]}),
 'repair-whitelist':()=>confirmLocal('整理当前兵种的失效引用','仅移除不存在的槽位和装备引用。若整理后会把某槽位变成“允许全部”，将停止操作；先在该槽位勾选至少一个有效选项，再整理。',()=>{mutate('已整理当前编制的失效引用',()=>{const c=role(),r=rule();for(const [id,allowed] of Object.entries(r.allowedEntries)){if(!c.slotDefinitions.some(s=>s.id===id)){delete r.allowedEntries[id];continue}const valid=allowed.filter(e=>(c.slots[id]||[]).some(x=>x.id===e));if(allowed.length&&!valid.length&&(c.slots[id]||[]).length)throw Error(id+' 的有效可选范围为空，请先在此槽位勾选至少一个现有装备。');r.allowedEntries[id]=valid}});closeModal()}),
 'new-vehicle':()=>mutate('已添加载具，请核对车型与生成位置',()=>{const vs=formation().vehicles;if(vs.length>=64)throw Error('最多 64 辆载具');vs.push({id:newId('vehicle'),displayName:'新运输车',entityId:'superbwarfare:truck',offsetX:0,offsetY:0,offsetZ:6,yaw:0,replenishmentCooldownSeconds:-1})}),
 'copy-vehicle':el=>mutate('已复制载具，请调整位置避免重叠',()=>{const vs=formation().vehicles;if(vs.length>=64)throw Error('最多 64 辆载具');const v=copy(vs[Number(el.dataset.index)]);v.id=newId('vehicle');vs.push(v)}),
 'delete-vehicle':el=>mutate('已移除载具',()=>{const fm=formation(),v=fm.vehicles[Number(el.dataset.index)];fm.vehicles.splice(Number(el.dataset.index),1);fm.capabilities.respawn.mobileSpawnVehicleIds=fm.capabilities.respawn.mobileSpawnVehicleIds.filter(x=>x!==v.id)})
};
document.addEventListener('click',ev=>{const el=ev.target.closest('[data-action]');if(!el||el.disabled)return;try{actions[el.dataset.action]?.(el)}catch(e){showError(e.message)}});
document.addEventListener('change',ev=>{const el=ev.target;if(el.id==='faction-picker'){state.factionId=el.value;state.formationId='';state.classId='';state.slotId='';state.entryId='';render();return}if(el.dataset.bind===undefined)return;const b=bindings[Number(el.dataset.bind)];if(!b)return;if(el.validity&&!el.validity.valid){el.reportValidity();render();return}const v=b.type==='checkbox'?el.checked:['number','range'].includes(b.type)?Number(el.value):el.value;if(['number','range'].includes(b.type)&&(el.value===''||!Number.isFinite(v))){showError('请填写有效数字');render();return}try{mutate('已更新配置',()=>b.fn(v))}catch(err){showError(err.message)};});
document.addEventListener('input',ev=>{if(ev.target.id==='library-search')renderLibrary(ev.target.value)});
async function loadFile(file){if(file.size>8*1024*1024)throw Error('文件超过 8 MiB');const text=await file.text();const raw=C.parse(text);let next,base,source;if(raw.format==='wok_infantry_editor_project'){if(raw.version!==1||!raw.base||!raw.catalog)throw Error('工程文件缺少基线或版本不支持');next=raw.catalog;base=raw.base;source=raw.sourceName||file.name;}else{next=C.parse(text);base=copy(next);source=file.name;}
 const basic=x=>x?.format==='wok_infantry_catalog'&&x.version===1&&Array.isArray(x?.formations?.factions)&&Array.isArray(x?.loadouts?.classes);if(!basic(next)||!basic(base))throw Error('请选择完整阵营配装数据包或本编辑器工程文件，不能只打开单份 loadouts.json');
 C.assertEditable(next);C.assertEditable(base);
 if(fileMode==='merge'){if(raw.format==='wok_infantry_editor_project')throw Error('请选择从游戏刚导出的完整数据包作为最新基线');const res=C.mergeCatalog(state.base,state.catalog,next);if(res.conflicts.length){showModal('发现同时修改的内容',`<p>以下字段在工程和最新配置中都发生了变化，尚未应用合并。请将工程文件与最新数据包一并交给导入负责人处理。</p><pre>${esc(res.conflicts.map(x=>typeof x==='string'?x:JSON.stringify(x)).join('\n'))}</pre><div class="actions">${button('close-modal','保留当前工程')}</div>`);return}mutate('已合并最新配置并保留本次修改',()=>{state.catalog=res.catalog;state.base=copy(next);state.source=file.name;state.kind='file'});return;}
 const apply=()=>{state.catalog=copy(next);state.base=copy(base);state.source=source;state.kind='file';state.dirty=false;undo=[];render();autosave();closeModal();message('已打开 '+file.name)};if(state.dirty)confirmLocal('打开另一份文件','当前草稿会被替换。请先保存工程以保留未交付的修改；取消可返回保存。',apply);else apply();}
$('file').addEventListener('change',async ev=>{const file=ev.target.files[0];if(!file)return;try{await loadFile(file)}catch(e){showError(e.message)}finally{ev.target.value=''}});
window.addEventListener('beforeunload',ev=>{if(state.dirty){ev.preventDefault();ev.returnValue=''}});
render();
try{const saved=localStorage.getItem('wok-infantry-editor-v1');if(saved){const p=JSON.parse(saved);if(p.format==='wok_infantry_editor_project'&&p.version===1&&p.catalog&&p.base){C.assertEditable(p.catalog);C.assertEditable(p.base);modalAction=()=>{state.catalog=p.catalog;state.base=p.base;state.source=p.sourceName||'浏览器草稿';state.kind='file';state.dirty=true;render();closeModal();message('已恢复上次草稿')};showModal('继续上次编辑',`<p>此浏览器保存了 ${esc(p.savedAt||'上次')} 的草稿。</p><div class="actions">${button('close-modal','使用随包配置')}${button('modal-confirm','恢复草稿','primary')}</div>`)}}}catch{}
})();
